Repository comixcraft/Editor, pull requests merged in 2024-05, with the labels that each got.

#25 Cxc 174 layers management redo redo
  components/ComicPanels.vue
  components/DragResizeRotate.vue
  components/EditionMenu.vue
  components/LayerObject.vue
  components/WrapperCanvas.vue
  package-lock.json
  package.json
  pages/editor.vue
  utils/Classes/Element.js
  utils/Classes/Panel.js
  utils/buses.js
Labels: enhancement

#41 CXC-309: responsive panels
  assets/scss/_variables.scss
  components/ComicPanels.vue
  components/WrapperCanvas.vue
  config/templatePanelConfig.js
  config/templateStripConfig.js
Labels: enhancement

#46 CXC-364-Reset-filter-and-search-on-each-change
  components/CatalogLayout.vue
  components/CatalogSearch.vue
  components/CatalogSubNavigation.vue
Labels: bugfix

#50 CXC-388-Change-count-of-panels
  components/ComicPanels.vue
Labels: bugfix

#51 Cxc 387 keep handles and edition menu on top
  components/DragResizeRotate.vue
Labels: bugfix

#52 CXC-384: template and draft selection
  pages/index.vue
Labels: bugfix

#53 Cxc 382 pop up styling on desktop
  components/DecisionPopUp.vue
  components/OverlayModal.vue
Labels: bugfix

#48 Guideline for test and PR
  git-guideline.md
  pr-guideline.md
  public/guidelines/prComment.png
  public/guidelines/topOfPR.png
  test-procedure-guideline.md
Labels: documentation

#59 Cxc 360 arrow icon glitches out
  assets/scss/_vue3-drr.scss
  assets/scss/styles.scss
  pages/editor.vue
  pages/export.vue
  public/rotate.svg
Labels: bugfix

#49 Cxc 386 sub category tabs not fixed sticky
  components/CatalogContainer.vue
  components/CatalogLayout.vue
  components/CatalogSearch.vue
  components/CatalogSubNavigation.vue
  components/OverlayModal.vue
  pages/editor.vue
Labels: bugfix

#60 Cxc 376 buttons overlap content
  pages/export.vue
  pages/index.vue
Labels: bugfix

#57 CXC-392-Category-Styling
  assets/scss/_variables.scss
  components/CatalogNavigation.vue
  components/CatalogSubNavigation.vue
  pages/editor.vue
Labels: bugfix

#61 Create the review guideline
  public/guidelines/ReviewFinish.png
  public/guidelines/reviewDelete.png
  public/guidelines/reviewFilesChanged.png
  public/guidelines/reviewResolve.png
  public/guidelines/reviewSquash.png
  public/guidelines/reviewViewed.png
  review-guideline.md
Labels: documentation

#55 CXC-Top-navigation-is-inconsistent
  assets/scss/_navigation.scss
  pages/editor.vue
  pages/export.vue
  pages/index.vue
Labels: bugfix

#58 add: drag and drop for layer option
  components/LayerObject.vue
Labels: bugfix

#56 Cxc 159 preview
  component-guidelines.md
  components/OverlayModal.vue
  components/PreviewCanvas.vue
  components/ScreenOverlay.vue
  pages/editor.vue
  pages/export.vue
  pages/index.vue
  stores/useComicStore.js
  utils/Classes/Comic.js
Labels: enhancement

#69 CXC-340-Impressum
  assets/scss/_button.scss
  components/FooterComponent.vue
  pages/export.vue
  pages/impressum.vue
  pages/index.vue
Labels: enhancement

#73 Cxc 178 undo redo actions
  assets/scss/_button.scss
  components/ComicPanels.vue
  components/DragResizeRotate.vue
  components/LayerObject.vue
  components/TextEditor.vue
  components/WrapperCanvas.vue
  pages/editor.vue
  utils/Classes/Element.js
  utils/Classes/Panel.js
Labels: enhancement

#75 add: check if user did something and if unload call is from body
  assets/scss/styles.scss
  pages/editor.vue
  pages/export.vue
Labels: bugfix

#77 add user-select: none to topnav and search
  components/CatalogLayout.vue
  pages/editor.vue
  pages/export.vue
Labels: bugfix

#83 CXC-422: text resizing button hidden
  components/TextEditor.vue
Labels: bugfix

#79 Cxc 390 scroll bar behavior
  components/CatalogContainer.vue
  components/CatalogSubNavigation.vue
  pages/editor.vue
Labels: bugfix

#81 CXC-424 Adjust Hover States for subnavigation and navigation
  components/CatalogImagePreview.vue
  components/CatalogNavigation.vue
  components/CatalogSearch.vue
  components/CatalogSubNavigation.vue
  components/DragResizeRotate.vue
  components/TemplateDisplay.vue
  pages/editor.vue
  pages/index.vue
Labels: bugfix

#87 Cxc 412 catalog title font size
  components/CatalogLayout.vue
  pages/editor.vue
Labels: bugfix

#89 fix pop-up not showing on export
  pages/export.vue
Labels: bugfix

#91 Cxc 406 scrolling with open pop up
  components/OverlayModal.vue
Labels: bugfix

#88 CXC-416: can't select category after closing it
  components/CatalogLayout.vue
  components/CatalogNavigation.vue
  pages/editor.vue
Labels: bugfix

#92 duplicate image and change path
  public/TextSymbol.png
  utils/Classes/Text.js
Labels: bugfix

#82 CXC-419 Layer Management scrollbars
  components/LayerObject.vue
  pages/editor.vue
Labels: bugfix

#93 CXC-433: double tap on chrome
  components/DragResizeRotate.vue
Labels: bugfix

#96 CXC-366: update catalog with new structure
  README.md
  config/iconsConfig.js
  public/Barista And Coffee no expression.png
  public/catalog/Annotation/arrows/smallarrow.png
  public/catalog/Annotation/arrows/smallarrow2.png
  public/catalog/Annotation/arrows/smallarrow3.png
  public/catalog/Annotation/arrows/smallarrow4.png
  public/catalog/Annotation/arrows/smallarrow5.png
  public/catalog/Annotation/arrows/smallarrow6.png
  public/catalog/Annotation/arrows/smallarrow7.png
  public/catalog/Annotation/arrows/smallredarrow.png
  public/catalog/Annotation/arrows/smallredarrow2.png
  public/catalog/Annotation/arrows/smallredarrow3.png
  public/catalog/Annotation/arrows/smallredarrow4.png
  public/catalog/Annotation/lines/underline.png
  public/catalog/Annotation/others/checkmark.png
  public/catalog/Annotation/others/checkmark2.png
  public/catalog/Annotation/others/crossedout.png
  public/catalog/Annotation/others/crossedout2.png
  public/catalog/double_frame.png
  public/catalog/single_frame.png
  public/catalog/triple_frame.png
  server/assets/comixplain-catalog.js
Labels: documentation
